/** 12 种独立频道模块 — 每种独有布局 + 交互类型 */
export const CHANNEL_LAYOUTS = [
  {
    id: 'cinematic',
    label: 'CINEMATIC',
    tagline: '全幕沉浸',
    imageMode: 'fullbleed',
    interaction: 'parallax',
    veil: 'cinematic',
    glow: { x: 28, y: 72 },
  },
  {
    id: 'editorial',
    label: 'EDITORIAL',
    tagline: '杂志分屏',
    imageMode: 'splitRight',
    interaction: 'slideReveal',
    veil: 'editorial',
    glow: { x: 78, y: 48 },
  },
  {
    id: 'monument',
    label: 'MONUMENT',
    tagline: '纪念碑画幅',
    imageMode: 'card',
    interaction: 'tilt3d',
    veil: 'bottom',
    glow: { x: 50, y: 38 },
  },
  {
    id: 'prism',
    label: 'PRISM',
    tagline: '棱镜浮层',
    imageMode: 'fullbleed',
    interaction: 'glassPulse',
    veil: 'prism',
    glow: { x: 18, y: 52 },
  },
  {
    id: 'orbit',
    label: 'ORBIT',
    tagline: '轨道漂浮',
    imageMode: 'orbit',
    interaction: 'orbit',
    veil: 'radial',
    glow: { x: 50, y: 42 },
  },
  {
    id: 'peel',
    label: 'PEEL',
    tagline: '折页揭开',
    imageMode: 'peel',
    interaction: 'peel',
    veil: 'peel',
    glow: { x: 88, y: 12 },
  },
  {
    id: 'horizon',
    label: 'HORIZON',
    tagline: '地平线漫游',
    imageMode: 'panorama',
    interaction: 'panX',
    veil: 'horizon',
    glow: { x: 50, y: 82 },
  },
  {
    id: 'portal',
    label: 'PORTAL',
    tagline: '光圈门户',
    imageMode: 'portal',
    interaction: 'iris',
    veil: 'portal',
    glow: { x: 50, y: 50 },
  },
  {
    id: 'stack',
    label: 'STACK',
    tagline: '叠层展开',
    imageMode: 'stack',
    interaction: 'fan',
    veil: 'stack',
    glow: { x: 42, y: 54 },
  },
  {
    id: 'glitch',
    label: 'GLITCH',
    tagline: '信号扰动',
    imageMode: 'fullbleed',
    interaction: 'glitch',
    veil: 'glitch',
    glow: { x: 62, y: 38 },
  },
  {
    id: 'sweep',
    label: 'SWEEP',
    tagline: '光刃扫描',
    imageMode: 'diagonal',
    interaction: 'sweep',
    veil: 'sweep',
    glow: { x: 32, y: 28 },
  },
  {
    id: 'magnet',
    label: 'MAGNET',
    tagline: '磁悬浮',
    imageMode: 'floatCard',
    interaction: 'magnetic',
    veil: 'magnet',
    glow: { x: 50, y: 50 },
  },
];

export const getChannelLayout = (index) => CHANNEL_LAYOUTS[index % CHANNEL_LAYOUTS.length];
